### Loading all necessary libraries

In [108]:
import numpy as np
import pandas as pd

### Reading the dataset

In [109]:
df=pd.read_csv("survey.csv")
df.head(5)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

### Removing unnecessary columns

In [110]:
df.drop(['Timestamp', 'state', 'comments'], axis=1,inplace=True)

In [111]:
df.head(15)

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,33,Male,United States,NaN,Yes,No,Sometimes,6-25,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
6,35,Female,United States,NaN,Yes,Yes,Sometimes,1-5,Yes,Yes,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No
7,39,M,Canada,NaN,No,No,Never,1-5,Yes,Yes,...,Yes,Don't know,No,No,No,No,No,No,No,No
8,42,Female,United States,NaN,Yes,Yes,Sometimes,100-500,No,Yes,...,No,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No
9,23,Male,Canada,NaN,No,No,Never,26-100,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No
10,31,Male,United States,NaN,No,Yes,Sometimes,6-25,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No
11,29,male,Bulgaria,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Yes,Yes,Yes,Yes,Don't know,No
12,42,female,United States,NaN,Yes,Yes,Sometimes,26-100,No,No,...,Don't know,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes
13,36,Male,United States,NaN,Yes,No,Never,500-1000,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,No,Don't know,No
14,27,Male,Canada,NaN,No,No,Never,6-25,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,Maybe,Yes,Yes,No

In [112]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [113]:
df = df[(df['Age'] >= 18) & (df['Age'] <= 70)]

In [114]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [115]:
male_terms = [
    'male','m','man','cis male','cis man','mail','make','mal','male-ish',
    'maile','msle','male (cis)','malr'
]

df['Gender'] = df['Gender'].replace(male_terms, 'male')

In [116]:
female_terms = [
    'female','f','woman','female ','cis female','cis-female/femme',
    'femake','femail','female (cis)'
]

df['Gender'] = df['Gender'].replace(female_terms, 'female')

In [117]:
df.loc[~df['Gender'].isin(['male','female']), 'Gender'] = 'other'

In [118]:
df['Gender'].value_counts()

Gender
male      986
female    246
other      18
Name: count, dtype: int64

In [119]:
df.describe()

               Age
count  1250.000000
mean     32.044800
std       7.203076
min      18.000000
25%      27.000000
50%      31.000000
75%      36.000000
max      65.000000

### Handling missing values

In [120]:
df.isnull().sum().sum()

280

In [121]:
df.fillna("Unknown",inplace=True)

In [122]:
df.isnull().sum().sum()

0

In [123]:
x=df.drop("treatment",axis=1)
y=df["treatment"]

In [124]:
for i in x.columns:
    print(i,':','\n',x[i].unique(),'\n')

Age :
 [37 44 32 31 33 35 39 42 23 29 36 27 46 41 34 30 40 38 50 24 18 28 26 22
 19 25 45 21 43 56 60 54 55 48 20 57 58 47 62 51 65 49 53 61]

Gender :
 ['female' 'male' 'other']

Country :
 ['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Greece' 'Moldova' 'Georgia'
 'China' 'Czech Republic' 'Philippines']

self_employed :
 ['Unknown' 'Yes' 'No']

family_history :
 ['No' 'Yes']

work_interfere :
 ['Often' 'Rarely' 'Never' 'Sometimes' 'Unknown']

no_employees :
 ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

remote_work :
 ['No' 'Yes']

tech_company :
 ['Yes' 'No']

benefits :
 ['Yes' "Don't know" 'No']

care_options :
 ['Not sure' 'No' 'Yes']

wellness_program :
 ['No' "Don't know" 'Yes']

seek_help :
 ['Yes' "Don't know" 'No']

anonymity :
 ['Yes' "Don't know" 'No']

leave :
 ['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy']

mental_health_consequence :
 ['No' 'Maybe' 'Yes']

phys_health_consequence :
 ['No' 'Yes' 'Maybe']

coworkers :
 ['Some of them' 'No' 'Yes']

supervisor :
 ['Yes' 'No' 'Some of them']

mental_health_interview :
 ['No' 'Yes' 'Maybe']

phys_health_interview :
 ['Maybe' 'No' 'Yes']

mental_vs_physical :
 ['Yes' "Don't know" 'No']

obs_consequence :
 ['No' 'Yes']

### Encoding

In [125]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in x.columns:
    x[col] = le.fit_transform(x[col])

In [126]:
x.head(10)

,Age,Gender,Country,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,19,0,44,1,0,1,4,0,1,2,...,2,2,1,1,1,2,1,0,2,0
1,26,1,44,1,0,2,5,0,0,0,...,0,0,0,1,0,0,1,1,0,0
2,14,1,6,1,0,2,4,0,1,1,...,0,1,1,1,2,2,2,2,1,0
3,13,1,43,1,1,1,2,0,1,1,...,1,1,2,2,1,0,0,0,1,1
4,13,1,44,1,0,0,1,1,1,2,...,0,0,1,1,1,2,2,2,0,0
5,15,1,44,1,1,3,4,0,1,2,...,0,0,1,1,2,2,1,0,0,0
6,17,0,44,1,1,3,0,1,1,1,...,1,1,0,0,1,0,1,1,0,0
7,21,1,6,1,0,0,0,1,1,1,...,2,0,1,1,0,0,1,1,1,0
8,24,0,44,1,1,3,1,0,1,2,...,1,3,0,1,2,2,1,0,1,0
9,5,1,6,1,0,0,2,0,1,0,...,0,0,1,1,2,2,0,0,2,0

### Train-Test-Split the data

In [127]:
from sklearn.model_selection import train_test_split

In [128]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [129]:
print(x_train)

      Age  Gender  Country  self_employed  family_history  work_interfere  \
51     15       1       44              0               0               4
802    21       1       44              0               0               4
571    24       1       44              0               0               1
456     9       1        4              0               0               2
1140    8       1       26              0               0               1
...   ...     ...      ...            ...             ...             ...
719     9       1       44              0               0               4
910    30       1        0              0               0               3
1103   17       0       44              0               1               3
236    19       1        6              0               1               1
1067    8       1       44              0               0               0

      no_employees  remote_work  tech_company  benefits  ...  anonymity  \
51               1            1             1         0  ...          0
802              2            1             1         2  ...          0
571              5            0             1         2  ...          2
456              4            0             1         1  ...          0
1140             2            0             1         1  ...          2
...            ...          ...           ...       ...  ...        ...
719              2            0             1         2  ...          0
910              4            0             1         1  ...          0
1103             4            1             1         0  ...          0
236              2            0             1         2  ...          0
1067             5            0             0         2  ...          0

      leave  mental_health_consequence  phys_health_consequence  coworkers  \
51        0                          1                        1          1
802       0                          2                        0          0
571       2                          0                        0          2
456       2                          0                        1          1
1140      3                          1                        1          2
...     ...                        ...                      ...        ...
719       0                          1                        1          2
910       2                          2                        1          1
1103      2                          1                        1          2
236       0                          0                        1          1
1067      1                          0                        1          0

      supervisor  mental_health_interview  phys_health_interview  \
51             2                        0                      0
802            0                        1                      1
571            2                        0                      0
456            1                        1                      0
1140           2                        2                      2
...          ...                      ...                    ...
719            2                        1                      1
910            0                        1                      0
1103           1                        1                      1
236            1                        1                      2
1067           2                        1                      1

      mental_vs_physical  obs_consequence
51                     0                0
802                    0                0
571                    0                0
456                    1                0
1140                   0                0
...                  ...              ...
719                    0                0
910                    1                1
1103                   2                0
236                    0                0
1067                   0                0

[1000 rows x 23 columns]

In [130]:
print(x_test)

      Age  Gender  Country  self_employed  family_history  work_interfere  \
411    13       0       44              0               1               2
714    14       1       44              2               1               3
1121   26       1       43              0               0               3
702    19       1       44              0               1               3
237    16       1       43              0               1               4
...   ...     ...      ...            ...             ...             ...
229     8       1       43              2               0               3
1160   11       1       44              0               0               3
962    17       1       16              2               0               3
356    15       1       44              0               1               3
814    18       0       43              2               0               3

      no_employees  remote_work  tech_company  benefits  ...  anonymity  \
411              5            0             0         0  ...          0
714              0            1             1         2  ...          0
1121             5            0             0         1  ...          0
702              1            0             1         2  ...          2
237              4            0             1         1  ...          2
...            ...          ...           ...       ...  ...        ...
229              0            0             1         1  ...          0
1160             2            0             1         2  ...          0
962              2            1             0         0  ...          0
356              2            0             1         0  ...          0
814              0            1             1         0  ...          0

      leave  mental_health_consequence  phys_health_consequence  coworkers  \
411       3                          2                        0          0
714       3                          2                        0          1
1121      0                          0                        1          1
702       0                          0                        1          2
237       1                          1                        1          1
...     ...                        ...                      ...        ...
229       0                          0                        1          1
1160      0                          2                        1          1
962       1                          2                        0          2
356       0                          0                        1          1
814       0                          0                        1          1

      supervisor  mental_health_interview  phys_health_interview  \
411            0                        1                      0
714            0                        1                      1
1121           1                        1                      1
702            2                        1                      1
237            2                        1                      2
...          ...                      ...                    ...
229            1                        1                      0
1160           1                        1                      0
962            0                        1                      0
356            1                        1                      1
814            0                        1                      1

      mental_vs_physical  obs_consequence
411                    1                0
714                    1                0
1121                   1                0
702                    0                0
237                    1                1
...                  ...              ...
229                    2                0
1160                   0                0
962                    0                0
356                    0                0
814                    0                0

[250 rows x 23 columns]

In [131]:
print(y_train)

51       No
802      No
571     Yes
456      No
1140    Yes
       ...
719      No
910     Yes
1103     No
236     Yes
1067     No
Name: treatment, Length: 1000, dtype: object

In [132]:
print(y_test)

411     Yes
714     Yes
1121    Yes
702     Yes
237      No
       ...
229     Yes
1160    Yes
962     Yes
356     Yes
814      No
Name: treatment, Length: 250, dtype: object

### Model Training

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [138]:
dc=DecisionTreeClassifier()

In [139]:
dc = DecisionTreeClassifier(criterion = 'entropy',max_depth=5,
    min_samples_split=10,class_weight='balanced', random_state = 0)
dc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=5, min_samples_split=10, random_state=0)

In [140]:
y_pred = dc.predict(x_test)

In [141]:
y_test.value_counts()

treatment
Yes    128
No     122
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [142]:
print(confusion_matrix(y_test, y_pred))

[[ 88  34]
 [  6 122]]

In [143]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.84

In [144]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.94      0.72      0.81       122
         Yes       0.78      0.95      0.86       128

    accuracy                           0.84       250
   macro avg       0.86      0.84      0.84       250
weighted avg       0.86      0.84      0.84       250

In [145]:
print(dc.score(x_train, y_train))
print(dc.score(x_test, y_test))

0.83
0.84

### Comparing Decision Tree with Random Forest
### Decision Tree performed better (84% vs 80%), suggesting simpler data patterns

In [148]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200,
    max_depth=7,
    min_samples_split=10, random_state=0)
rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_rf))

from sklearn.metrics import accuracy_score
print("RF Accuracy:", accuracy_score(y_test, y_pred_rf))

[[ 89  33]
 [ 16 112]]
RF Accuracy: 0.804