### Loading all necessary libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("survey.csv")
df.head(5)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [3]:
df.drop(['Timestamp', 'state', 'comments'], axis=1,inplace=True)

In [4]:
df.head(15)

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,33,Male,United States,NaN,Yes,No,Sometimes,6-25,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
6,35,Female,United States,NaN,Yes,Yes,Sometimes,1-5,Yes,Yes,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No
7,39,M,Canada,NaN,No,No,Never,1-5,Yes,Yes,...,Yes,Don't know,No,No,No,No,No,No,No,No
8,42,Female,United States,NaN,Yes,Yes,Sometimes,100-500,No,Yes,...,No,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No
9,23,Male,Canada,NaN,No,No,Never,26-100,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No
10,31,Male,United States,NaN,No,Yes,Sometimes,6-25,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No
11,29,male,Bulgaria,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Yes,Yes,Yes,Yes,Don't know,No
12,42,female,United States,NaN,Yes,Yes,Sometimes,26-100,No,No,...,Don't know,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes
13,36,Male,United States,NaN,Yes,No,Never,500-1000,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,No,Don't know,No
14,27,Male,Canada,NaN,No,No,Never,6-25,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,Maybe,Yes,Yes,No

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
df = df[(df['Age'] >= 18) & (df['Age'] <= 70)]

In [7]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [8]:
male_terms = [
    'male','m','man','cis male','cis man','mail','make','mal','male-ish',
    'maile','msle','male (cis)','malr'
]

df['Gender'] = df['Gender'].replace(male_terms, 'male')

In [9]:
female_terms = [
    'female','f','woman','female ','cis female','cis-female/femme',
    'femake','femail','female (cis)'
]

df['Gender'] = df['Gender'].replace(female_terms, 'female')

In [10]:
df.loc[~df['Gender'].isin(['male','female']), 'Gender'] = 'other'

In [11]:
df['Gender'].value_counts()

Gender
male      986
female    246
other      18
Name: count, dtype: int64

In [12]:
df.describe()

               Age
count  1250.000000
mean     32.044800
std       7.203076
min      18.000000
25%      27.000000
50%      31.000000
75%      36.000000
max      65.000000

In [13]:
df.isnull().sum().sum()

280

In [14]:
df.fillna("Unknown",inplace=True)

In [15]:
df.isnull().sum().sum()

0

In [16]:
x=df.drop("treatment",axis=1)
y=df["treatment"]

In [17]:
for i in x.columns:
    print(i,':','\n',x[i].unique(),'\n')

Age :
 [37 44 32 31 33 35 39 42 23 29 36 27 46 41 34 30 40 38 50 24 18 28 26 22
 19 25 45 21 43 56 60 54 55 48 20 57 58 47 62 51 65 49 53 61]

Gender :
 ['female' 'male' 'other']

Country :
 ['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Greece' 'Moldova' 'Georgia'
 'China' 'Czech Republic' 'Philippines']

self_employed :
 ['Unknown' 'Yes' 'No']

family_history :
 ['No' 'Yes']

work_interfere :
 ['Often' 'Rarely' 'Never' 'Sometimes' 'Unknown']

no_employees :
 ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

remote_work :
 ['No' 'Yes']

tech_company :
 ['Yes' 'No']

benefits :
 ['Yes' "Don't know" 'No']

care_options :
 ['Not sure' 'No' 'Yes']

wellness_program :
 ['No' "Don't know" 'Yes']

seek_help :
 ['Yes' "Don't know" 'No']

anonymity :
 ['Yes' "Don't know" 'No']

leave :
 ['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy']

mental_health_consequence :
 ['No' 'Maybe' 'Yes']

phys_health_consequence :
 ['No' 'Yes' 'Maybe']

coworkers :
 ['Some of them' 'No' 'Yes']

supervisor :
 ['Yes' 'No' 'Some of them']

mental_health_interview :
 ['No' 'Yes' 'Maybe']

phys_health_interview :
 ['Maybe' 'No' 'Yes']

mental_vs_physical :
 ['Yes' "Don't know" 'No']

obs_consequence :
 ['No' 'Yes']

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

SyntaxError: expected ':' (1795752865.py, line 1)